In [1]:
import numpy as np

In [2]:
sigmoid  = lambda z: 1 / (1 + np.exp(-z))
dsigmoid = lambda z: sigmoid(z) * (1 - sigmoid(z))

In [3]:
w1=np.array([[.25, .5],
            [.05, -.25]])
w2=np.array([[.25, -.25]])
p=np.array([[.5, .5]]).T
b1=np.array([[0,0]]).T
b2=np.array([[0]]).T


In [4]:
n1=w1@p+b1
n1

array([[ 0.375],
       [-0.1  ]])

In [5]:
a1=sigmoid(n1)
a1

array([[0.5926666 ],
       [0.47502081]])

In [6]:
n2=w2@a1+b2
n2

array([[0.02941145]])

In [7]:
a2=sigmoid(n2)
a2

array([[0.50735233]])

In [8]:
dl2=(a2-1)*dsigmoid(n2)
dl2

array([[-0.12313529]])

In [9]:
w2-=dl2@p.T
w2

array([[ 0.31156764, -0.18843236]])

In [10]:
dl1=dl2*w2@dsigmoid(n1)
dl1

array([[-0.00347561]])

In [11]:
w1-=dl1@a1.T
w1

array([[ 0.25205988,  0.50165099],
       [ 0.05205988, -0.24834901]])

In [33]:
w1 = np.array([[.25, .5],
               [.05, -.25],
               [.25, -.25]])       

w2 = np.array([[.25, -.25, 0.5],   
               [.1,  .2,  -.1]])

w3 = np.array([[.25, -.25]])        

b1 = np.array([[.0, 0, 0]]).T       
b2 = np.array([[.0, 0]]).T         
b3 = np.array([[.0]]).T             

In [34]:
import numpy as np

# activation
sigmoid  = lambda z: 1/(1+np.exp(-z))
dsigmoid = lambda z: sigmoid(z)*(1-sigmoid(z))

lr = .1
losses=[]

for _ in range(10000):
    for i in range(len(p)):
        x, t = p[i].reshape(2,1), y[i]

        n1 = w1 @ x  + b1
        a1 = sigmoid(n1)

        n2 = w2 @ a1 + b2        
        a2 = sigmoid(n2)

        n3 = w3 @ a2 + b3          
        a3 = sigmoid(n3)


        dl3 = (a3 - t) * dsigmoid(n3)

        dl2 = (w3.T @ dl3) * dsigmoid(n2)  

        dl1 = (w2.T @ dl2) * dsigmoid(n1)

        w3 -= lr * (dl3 @ a2.T)
        w2 -= lr * (dl2 @ a1.T)
        w1 -= lr * (dl1 @ x.T)

        b3 -= lr * dl3
        b2 -= lr * dl2
        b1 -= lr * dl1

        loss = np.mean((a3 - t)**2)
        losses.append(loss)

In [35]:
def forward(w1, w2, w3, b1, b2, b3, x):
    n1 = w1 @ x  + b1
    a1 = sigmoid(n1)
    n2 = w2 @ a1 + b2
    a2 = sigmoid(n2)
    n3 = w3 @ a2 + b3
    a3 = sigmoid(n3)
    return a3

In [36]:
x=np.array([1,1]).reshape(2,1)
forward(w1, w2, w3, b1, b2, b3, x)

array([[0.50021253]])

In [37]:
dsigmoid(-0.25)

np.float64(0.24613408273759835)

In [38]:
-0.122*dsigmoid(-0.25)*(-0.25)

np.float64(0.007507089523496749)